spring:
  application:
    name: pricing-services
  profiles:
    active: dev
server:
  port: 8093
  servlet:
    context-path: /api
logging:
  level:
    root: TRACE
    org:
      apache:
        tomcat: INFO
    com.example.myapp: debug